apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboarding-depl
spec:
  selector:
    matchLabels:
      app: dashboarding
  replicas: 1
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: dashboarding
    spec:
      containers:
        - name: dashboarding
          image: dashboarding:0.0.1
          ports:
            - containerPort: 5170
          env:
          - name: DASHBOARDING_ENV
            value: containerized
          - name: DASHBOARDING_BACKEND_HOST
            value: dashbackend-svc
          - name: DASHBOARDING_BACKEND_PORT
            value: '3101'
---
apiVersion: v1
kind: Service
metadata:
  name: dashboarding-svc
spec:
  type: NodePort
  selector:
    app: dashboarding
  ports:
  - protocol: TCP
    port: 8100
    targetPort: 5170
    nodePort: 31100
  
